<tr>
                                                                                    <td align="center" valign="top" width="100%">
                                                                                        <table width="100%">
                                                                                            <tbody>
                                                                                                <tr>
                                                                                                    <td style="word-break:break-all" valign="top" width="50%">
                                                                                                        <div style="width:100%">
                                                                                                            <div style="width:100%;text-align:left;">
                                                                                                                <a href="http://www.gtfoundation.cn/_d276968607.htm" target="_blank" style="color:">
                                                                                                                    <font style="font-size:14px;color:#424242;font-weight:bold;line-height:20px;">
                                                                                                                        <span name="mynet_list_span_d2-275532881-2a11" style="width: 13px; background-image: url(&quot;/theme/Icon/3.gif&quot;); background-repeat: no-repeat; background-position: left center; font-size: 12px; display: inline-block; height: 13px; top: 3px; position: relative;">
                                                                                                                        </span>
																														 <a href="[field:arcurl/]" class="title ">[field:title/]</a>  
     
                                                                                                                    </font>
                                                                                                                </a>
                                                                                                            </div>
                                                                                                        </div>
                                                                                                        <div style="width:100%">
                                                                                                            <div style="width:100%;text-align:left;">
                                                                                                                <font id="276968607_summary">
                                                                                                                    <p class="intro "> [field:description/]... </p> 
                                                                                                                </font>
                                                                                                            </div>
                                                                                                        </div>
                                                                                                    </td>
                                                                                                </tr>
                                                                                            </tbody>
                                                                                        </table>
                                                                                    </td>
                                                                                </tr> 
                                                                                <tr>
																				  <td style="height:1px; padding:1px;border-top:dotted 1px #7F7F7F;" colspan="2">
                                                                                        <div style="height:2px;overflow:hidden;">
                                                                                        </div>
                                                                                    </td>
                                                                                </tr>