<tr>
                                                                                    <td align="center" valign="top" width="100%">
                                                                                        <table width="100%">
                                                                                            <tbody>
                                                                                                <tr>
                                                                                                    <td style="word-break:break-all" valign="top" width="50%">
                                                                                                        <div style="width:100%">
                                                                                                            <div style="width:100%;text-align:left;">
                                                                                                                <a href="http://www.gtfoundation.cn/_d276875992.htm" target="_blank" style="color:">
                                                                                                                    <span name="mynet_list_span_d2-1479-2a268" style="width: 13px; background-image: url(&quot;/theme/Icon/15.gif&quot;); background-repeat: no-repeat; background-position: left center; font-size: 12px; display: inline-block; height: 13px; top: 3px; position: relative;">
                                                                                                                    </span>
																													<a href='[field:arcurl/]'>[field:title/]</a>
                                                                                                                </a>
                                                                                                            </div>
                                                                                                        </div>
                                                                                                    </td>
                                                                                                </tr>
                                                                                            </tbody>
                                                                                        </table>
                                                                                    </td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td style="height:1px; padding:1px;" colspan="2">
                                                                                        <div style="height:2px;overflow:hidden;">
                                                                                        </div>
                                                                                    </td>
                                                                                </tr>