<tr>
                                                                                    <td align="center" valign="top" width="100%">
                                                                                        <div style="text-align:left;height:atuo;!important;height:auto;">
                                                                                            <a href="http://www.gtfoundation.cn/_d276968607.htm" target="_blank" style="color:">
                                                                                                <span name="mynet_list_span_d2-1479-2a269" style="width: 13px; background-image: url(&quot;/theme/Icon/15.gif&quot;); background-repeat: no-repeat; background-position: left center; font-size: 12px; display: inline-block; height: 13px; top: 3px; position: relative;">
                                                                                                </span>
																								<a href='[field:arcurl/]'>[field:title/]</a>
                                                                                            </a>
                                                                                        </div>
                                                                                    </td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td style="height:1px; padding:1px;" colspan="2">
                                                                                        <div style="height:2px;overflow:hidden;">
                                                                                        </div>
                                                                                    </td>
                                                                                </tr>