<tr>
                                                                                                                            <td class="mynetMenuBox mynetMenuGrad d2-275532879-2a8_Normal_Td" onmouseout="if(!this.contains(event.toElement)) mynetMenuRootOut(null,this);mynetMenuSetTimeout(1000);"
                                                                                                                            onmouseover="if(!this.contains(event.fromElement)){mynetMenuRootOver(null,this);mynetNavMenuPopup(null,this,2,0,window,null,null,'2');mynetMenuSetTimeout(100000);}"
                                                                                                                            style="width:100%" id="d2-275532879-2a8_0">
                                                                                                                                <div class="d2-275532879-2a8_Normal_Div">
                                                                                                                                    <img src="[field:global.cfg_templets_skin/]/images/_c_ADnfaMa0GiVuRtBm9OsQRwijygAGFDPGyBs_M5S63ZHQMaBqKBDT3gWgV.png"
                                                                                                                                    class="m_bkimage" align="middle" width="100%">
                                                                                                                                    <span class="d2-275532879-2a8_Normal_Span">
                                                                                                                                        <a href="[field:arcurl/]">[field:title/]</a>  
                                                                                                                                    </span>
                                                                                                                                </div>
                                                                                                                            </td>
                                                                                                                        </tr>
                                                                                                                        <tr>
                                                                                                                            <td align="center" width="1px">
                                                                                                                                <img src="[field:global.cfg_templets_skin/]/images/_c_8dzRY1tNCfmpCCDL_GdtktWrKFgUAS27RWAHKcBpLrtla7raaWwV9UDgu.png"
                                                                                                                                align="middle">
                                                                                                                            </td>
                                                                                                                        </tr>