<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /dd57/uploads/uploads/allimg/150324/1-150324211503.jpg ",93,266);
$z[1][4]['ddimg']="/dd57/uploads/uploads/allimg/150324/1-150324211503.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="135";
$z[1][4]['height']="180";
$z[2]=Array("img"," /dd57/uploads/uploads/allimg/150324/1-150324211504.jpg ",268,441);
$z[2][4]['ddimg']="/dd57/uploads/uploads/allimg/150324/1-150324211504.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="580";
$z[2][4]['height']="386";
$z[3]=Array("img"," /dd57/uploads/uploads/allimg/150324/1-150324211607.jpg ",443,616);
$z[3][4]['ddimg']="/dd57/uploads/uploads/allimg/150324/1-150324211607.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="135";
$z[3][4]['height']="180";
$z[4]=Array("img"," /dd57/uploads/uploads/allimg/150324/1-150324211607-50.jpg ",618,797);
$z[4][4]['ddimg']="/dd57/uploads/uploads/allimg/150324/1-150324211607-50.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="580";
$z[4][4]['height']="386";

?>