<?php
$z[0]=Array("global","",44,76);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",232,258);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",301,323);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",367,418);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",4727,4759);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",6132,6169);
$z[5][4]['filename']="header.htm";
$z[6]=Array("global","",10704,10759);
$z[6][4]['name']="keyword";
$z[6][4]['function']="RemoveXSS(@me)";
$z[7]=Array("list","\r\n                <tr>\r\n                    <td align=\"Left\" width=\"100%\" valign=\"top\">\r\n                        <a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a> \r\n                    </td>\r\n                </tr>\r\n				",12197,12463);
$z[7][4]['perpage']="10";
$z[8]=Array("pagelist","",12911,12940);
$z[8][4]['listsize']="4";
$z[9]=Array("include","",28889,28926);
$z[9][4]['filename']="footer.htm";

?>