<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5qCP55uu5ZCN56ewMQ==');
$cfg_Cs[2]=array(1,1,1,'5qCP55uu5ZCN56ewMTE=');
$cfg_Cs[3]=array(2,1,1,'5qCP55uu5ZCN56ewMTEx');
$cfg_Cs[4]=array(0,1,1,'5Z+66YeR5Lya');
$cfg_Cs[5]=array(4,3,1,'5L+h5oGv5YWs5byA');
$cfg_Cs[6]=array(4,1,1,'5paw6Ze75Lit5b+D');
$cfg_Cs[7]=array(4,1,1,'5YWs55uK6aG555uu');
$cfg_Cs[8]=array(4,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[9]=array(4,1,1,'5YWs55uK5o2Q6LWg');
$cfg_Cs[10]=array(4,1,1,'5b+X5oS/6ICF');
$cfg_Cs[11]=array(6,1,1,'5pyA5paw5Yqo5oCB');
$cfg_Cs[12]=array(6,1,1,'5YWs55uK6KeG54K5');
?>